version: "3.9"
services:
  web:
    build: .
    container_name: visionqa-frontend
    env_file:
      - ../.env
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL:-http://localhost:8000}
    ports:
      - "${APP_FRONTEND_PORT:-3000}:3000"
    restart: unless-stopped
    volumes:
      - ./:/app 